Email address save doc
wevote/WeVoteServer pull request #1902
Opened 2022-08-02 23:02 UTC by Jakaboy3

#1888
@yuli48

2022-08-03 00:14 UTC, DaleMcGrew requested changes
Thank you again Yulisa and Jack, could you also please roll back the changes to package-lock.json?

2022-08-03 00:14 UTC, DaleMcGrew commented on config/base.py
> +import sys
Thank you Yulisa and Jack! Could you please roll back (undo) your changes to the config/base.py file?

2022-08-08 17:29 UTC, DaleMcGrew commented on config/base.py
> +import sys
Could you also please roll back the changes to package-lock.json? Thank you in advance.

2022-08-08 22:14 UTC, Jakaboy3 commented
@DaleMcGrew We made another pull request with only one file since my partner and I do not know how to roll back the code.

2022-08-09 11:50 UTC, closed without merging