Added Has Email checkbox on Candidates Admin page (WV-93)
wevote/WeVoteServer pull request #2287
Opened 2024-01-09 00:44 UTC by hesamshayegan

2024-01-11 14:03 UTC, DaleMcGrew requested changes
Thank you @hesamshayegan, this is almost there, pending my two comments. Great work!

2024-01-11 14:03 UTC, DaleMcGrew commented on candidate/views_admin.py
> +            candidate_query = candidate_query.annotate(candidate_email2_length=Length('candidate_email2'))
Hello @hesamshayegan, for the Candidate object in WeVoteServer/candidate/models.py we only have one field (no "candidate_email2" or "candidate_email3".

2024-01-11 14:03 UTC, DaleMcGrew commented on templates/candidate/candidate_list.html
>      {# Turn on/off review mode #}
Please move this "Turn on/off review mode" comment to be above "review_mode_id" code, and add a new comment here saying something like "Limit list to only show candidates with an email address".

2024-01-12 19:42 UTC, hesamshayegan commented
Hi @DaleMcGrew, Thanks for you comments. I updated candidate_list.html in templates and removed the second and third emails from views_admin.py.

2024-01-20 15:59 UTC, DaleMcGrew commented
Thank you @hesamshayegan! 👍

2024-01-20 15:59 UTC, merged