Wv 861 add next page UI
wevote/WeVoteServer pull request #2821
Opened 2024-12-10 03:22 UTC by itcreativeusa

1)Implemented backend logic to support pagination with total_count, items_per_page, start_index, and end_index.
2) Added previous_page_url and next_page_url for navigation.
3) Conditionally hid pagination UI when items fit on a single page.
4)Updated the frontend to display "Previous" and "Next" links with the current page number.

2025-01-17 15:10 UTC, DaleMcGrew requested changes
Hi Katerenya, overall you are on the right track. I have these comments for your next iteration. Thank you!

2025-01-17 15:10 UTC, DaleMcGrew commented on templates/politician/politician_list.html
> +<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
Hi Katerenya, we shouldn't have to include this here because jquery is already included in WeVoteServer/templates/template_base.html on line 24. You can upgrade that version in that file if you need a newer version.

2025-01-17 15:10 UTC, DaleMcGrew commented on politician/views_admin.py
> +        'politician_list': politician_list,
Please add these template variables in alphabetical order, because that helps us make sure we don't duplicate existing variables. (I see "politician_list" and "politician_search" for example are already passed in further down in this template_values dict.)

2025-01-17 15:10 UTC, DaleMcGrew commented on politician/views_admin.py
> +    politician_list = politician_query.order_by("politician_name")[start_index:end_index]
We have already retrieved politician_list above, and augmented it with data from the Representative table. This replaces that work with a brand new query. I think this pagination logic should be included up around lines 992-996 where the current retrieve is happening:

        if not positive_value_exists(show_all):
            politician_list = politician_query.order_by('politician_name')[:25]
        else:
            # We still want to limit to 200
            politician_list = politician_query.order_by('politician_name')[:200]

2025-01-17 15:10 UTC, DaleMcGrew commented on templates/politician/politician_list.html
> +    <input type="hidden" name="politician_search" value="{{ politician_search|default_if_none:'' }}" />
politician_search is already being included in the form down below on your line 74 in an input, and doesn't need to be added here as a hidden value.

2025-01-17 15:10 UTC, DaleMcGrew commented on templates/politician/politician_list.html
> +    <input type="hidden" name="show_all" value="{{ show_all|default_if_none:0 }}" />
show_all is already included below as a checkbox, and doesn't need to be included here as a hidden value.

2025-01-17 15:10 UTC, DaleMcGrew commented on templates/politician/politician_list.html
> +    <input type="hidden" name="exclude_politician_analysis_done" value="{{ exclude_politician_analysis_done|default_if_none:0 }}" />
exclude_politician_analysis_done is already included below as a checkbox, and doesn't need to be included here as a hidden value.

2025-01-28 20:53 UTC, itcreativeusa commented
https://github.com/user-attachments/assets/682c1faa-1ef2-4587-9173-1432f1c8c577

2025-01-29 00:01 UTC, itcreativeusa commented
this  screen recording shows my last commit : [fix reloading to page 1 if state changed or checkbox]. 
 With this changes It doesn't go on page 1 or reloads if state was changed or checkbox checked.(https://github.com/wevote/WeVoteServer/pull/2821/commits/0cab9f286b359541fd0a4607351e0f33d490b910)
https://github.com/user-attachments/assets/f9afdc48-e7c1-43b8-a796-48cd6cb54aa8

2025-02-05 23:43 UTC, DaleMcGrew commented
👍 Thank you for working through all of the challenges of this page!

2025-02-05 23:43 UTC, merged